from __future__ import annotations

from math import cos, pi, sin
from pathlib import Path

from .box_settings import BoxSettings
from .geometry import Panel, Point


class GcodeGenerator:
    def write(
        self, panels: list[Panel], settings: BoxSettings, output_path: Path
    ) -> None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8") as gcode_file:
            gcode_file.write("%\n")
            gcode_file.write(f"({settings.job_name} generated by box-creator)\n")
            gcode_file.write("(GRBL compatible, millimetres, absolute positioning)\n")
            gcode_file.write(
                f"(stock {settings.stock_width:.3f} x {settings.stock_height:.3f} mm)\n"
            )
            gcode_file.write("G21\nG90\nG94\n")
            gcode_file.write(f"G0 Z{settings.safe_height:.3f}\n")
            gcode_file.write(f"S{settings.spindle_speed:d} M3\n")
            for stock_index, stock_panels in self._panels_by_stock(panels):
                if stock_index > 0:
                    gcode_file.write("M5\n")
                    gcode_file.write(f"M0 (load stock sheet {stock_index + 1})\n")
                    gcode_file.write(f"S{settings.spindle_speed:d} M3\n")
                gcode_file.write(f"(stock sheet {stock_index + 1})\n")
                local_panels = [self._local_panel(panel) for panel in stock_panels]
                self._write_relief_holes(gcode_file, local_panels, settings)
                self._write_panel_profiles(gcode_file, local_panels, settings)
            gcode_file.write("M5\n")
            gcode_file.write(f"G0 Z{settings.safe_height:.3f}\n")
            gcode_file.write("M30\n%\n")

    def _panels_by_stock(self, panels: list[Panel]) -> list[tuple[int, list[Panel]]]:
        stock_indexes = sorted({panel.stock_index for panel in panels})
        return [
            (
                stock_index,
                [panel for panel in panels if panel.stock_index == stock_index],
            )
            for stock_index in stock_indexes
        ]

    def _local_panel(self, panel: Panel) -> Panel:
        offset_x = panel.stock_origin_x
        offset_y = panel.stock_origin_y
        return Panel(
            name=panel.name,
            width=panel.width,
            height=panel.height,
            origin_x=panel.origin_x - offset_x,
            origin_y=panel.origin_y - offset_y,
            outline=[
                Point(point.x - offset_x, point.y - offset_y) for point in panel.outline
            ],
            relief_points=[
                Point(point.x - offset_x, point.y - offset_y)
                for point in panel.relief_points
            ],
            stock_index=panel.stock_index,
            stock_origin_x=0.0,
            stock_origin_y=0.0,
        )

    def _write_relief_holes(
        self, gcode_file, panels: list[Panel], settings: BoxSettings
    ) -> None:
        radius = max(settings.relief_diameter * 0.5, settings.bit_diameter * 0.5)
        cutter_radius = settings.bit_diameter * 0.5
        toolpath_radius = max(0.0, radius - cutter_radius)
        if radius <= 0.0:
            return
        gcode_file.write(f"(corner relief diameter {radius * 2.0:.3f} mm)\n")
        for panel in panels:
            if not panel.relief_points:
                continue
            gcode_file.write(f"(relief holes for {panel.name})\n")
            for point in panel.relief_points:
                self._write_circle_pocket(gcode_file, point, toolpath_radius, settings)

    def _write_panel_profiles(
        self, gcode_file, panels: list[Panel], settings: BoxSettings
    ) -> None:
        gcode_file.write(f"(profile cut with {settings.bit_diameter:.3f} mm cutter)\n")
        for panel in panels:
            gcode_file.write(f"({panel.name} panel)\n")
            current_depth = 0.0
            while current_depth > settings.final_cut_depth:
                current_depth = max(
                    current_depth - settings.cut_depth_step, settings.final_cut_depth
                )
                self._write_profile_pass(gcode_file, panel, current_depth, settings)

    def _write_profile_pass(
        self, gcode_file, panel: Panel, depth: float, settings: BoxSettings
    ) -> None:
        points = panel.outline
        if len(points) < 2:
            return
        start = points[0]
        gcode_file.write(f"G0 X{start.x:.3f} Y{start.y:.3f}\n")
        gcode_file.write(f"G0 Z{settings.surface_height:.3f}\n")
        gcode_file.write(f"G1 Z{depth:.3f} F{settings.plunge_rate:d}\n")
        gcode_file.write(f"G1 F{settings.feed_rate:d}\n")
        for start, end in zip(points, points[1:]):
            if settings.include_tabs and self._is_bounding_edge(panel, start, end):
                self._write_segment_with_tabs(gcode_file, start, end, depth, settings)
            else:
                gcode_file.write(f"G1 X{end.x:.3f} Y{end.y:.3f}\n")
        gcode_file.write(f"G0 Z{settings.safe_height:.3f}\n")

    def _write_segment_with_tabs(
        self, gcode_file, start: Point, end: Point, depth: float, settings: BoxSettings
    ) -> None:
        dx = end.x - start.x
        dy = end.y - start.y
        length = (dx * dx + dy * dy) ** 0.5
        if length < settings.tab_width * 2.0:
            gcode_file.write(f"G1 X{end.x:.3f} Y{end.y:.3f}\n")
            return
        tab_count = max(1, int(length // 85.0))
        ranges = []
        for index in range(tab_count):
            center = length * (index + 1) / (tab_count + 1)
            ranges.append(
                (center - settings.tab_width * 0.5, center + settings.tab_width * 0.5)
            )
        current = 0.0
        for tab_start, tab_end in ranges:
            self._move_along_segment(
                gcode_file, start, dx, dy, length, tab_start, depth
            )
            if depth < -settings.tab_height:
                gcode_file.write(
                    f"G1 Z{-settings.tab_height:.3f} F{settings.plunge_rate:d}\n"
                )
            self._move_along_segment(
                gcode_file,
                start,
                dx,
                dy,
                length,
                tab_end,
                max(depth, -settings.tab_height),
            )
            if depth < -settings.tab_height:
                gcode_file.write(f"G1 Z{depth:.3f} F{settings.plunge_rate:d}\n")
            current = tab_end
        if current < length:
            gcode_file.write(f"G1 X{end.x:.3f} Y{end.y:.3f}\n")

    def _move_along_segment(
        self,
        gcode_file,
        start: Point,
        dx: float,
        dy: float,
        length: float,
        distance: float,
        depth: float,
    ) -> None:
        clamped = max(0.0, min(length, distance))
        ratio = clamped / length
        x_pos = start.x + dx * ratio
        y_pos = start.y + dy * ratio
        gcode_file.write(f"G1 X{x_pos:.3f} Y{y_pos:.3f}\n")

    def _write_circle_pocket(
        self, gcode_file, center: Point, radius: float, settings: BoxSettings
    ) -> None:
        gcode_file.write(f"G0 X{center.x + radius:.3f} Y{center.y:.3f}\n")
        gcode_file.write(f"G0 Z{settings.surface_height:.3f}\n")
        current_depth = 0.0
        while current_depth > settings.final_cut_depth:
            current_depth = max(
                current_depth - settings.cut_depth_step, settings.final_cut_depth
            )
            gcode_file.write(f"G1 Z{current_depth:.3f} F{settings.plunge_rate:d}\n")
            if radius <= 0.001:
                gcode_file.write(
                    f"G1 X{center.x:.3f} Y{center.y:.3f} F{settings.feed_rate:d}\n"
                )
                continue
            gcode_file.write(f"G1 F{settings.feed_rate:d}\n")
            for step in range(1, 33):
                angle = (2.0 * pi * step) / 32.0
                x_pos = center.x + cos(angle) * radius
                y_pos = center.y + sin(angle) * radius
                gcode_file.write(f"G1 X{x_pos:.3f} Y{y_pos:.3f}\n")
        gcode_file.write(f"G0 Z{settings.safe_height:.3f}\n")

    def _is_bounding_edge(self, panel: Panel, start: Point, end: Point) -> bool:
        min_x, max_x, min_y, max_y = panel.bounds
        tolerance = 0.001
        return (
            abs(start.x - end.x) < tolerance
            and (abs(start.x - min_x) < tolerance or abs(start.x - max_x) < tolerance)
        ) or (
            abs(start.y - end.y) < tolerance
            and (abs(start.y - min_y) < tolerance or abs(start.y - max_y) < tolerance)
        )
