from __future__ import annotations

from io import StringIO
from pathlib import Path

from .box_settings import BoxSettings
from .geometry import Panel, Point


class GcodeGenerator:
    def generate(self, panels: list[Panel], settings: BoxSettings) -> str:
        gcode_file = StringIO()
        gcode_file.write("%\n")
        gcode_file.write(f"({settings.job_name} generated by box-creator)\n")
        gcode_file.write("(GRBL compatible, millimetres, absolute positioning)\n")
        gcode_file.write(
            f"(stock {settings.stock_width:.3f} x {settings.stock_height:.3f} mm)\n"
        )
        gcode_file.write("G21\nG90\nG94\n")
        gcode_file.write(f"G0 Z{settings.safe_height:.3f}\n")
        gcode_file.write(f"S{settings.spindle_speed:d} M3\n")
        for stock_index, stock_panels in self._panels_by_stock(panels):
            if stock_index > 0:
                gcode_file.write("M5\n")
                gcode_file.write(f"M0 (load stock sheet {stock_index + 1})\n")
                gcode_file.write(f"S{settings.spindle_speed:d} M3\n")
            gcode_file.write(f"(stock sheet {stock_index + 1})\n")
            local_panels = [self._local_panel(panel) for panel in stock_panels]
            self._write_panel_profiles(gcode_file, local_panels, settings)
        gcode_file.write("M5\n")
        gcode_file.write(f"G0 Z{settings.safe_height:.3f}\n")
        gcode_file.write("M30\n%\n")
        return gcode_file.getvalue()

    def write(
        self, panels: list[Panel], settings: BoxSettings, output_path: Path
    ) -> None:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(self.generate(panels, settings), encoding="utf-8")

    def _panels_by_stock(self, panels: list[Panel]) -> list[tuple[int, list[Panel]]]:
        stock_indexes = sorted({panel.stock_index for panel in panels})
        return [
            (
                stock_index,
                [panel for panel in panels if panel.stock_index == stock_index],
            )
            for stock_index in stock_indexes
        ]

    def _local_panel(self, panel: Panel) -> Panel:
        offset_x = panel.stock_origin_x
        offset_y = panel.stock_origin_y
        return Panel(
            name=panel.name,
            width=panel.width,
            height=panel.height,
            origin_x=panel.origin_x - offset_x,
            origin_y=panel.origin_y - offset_y,
            outline=[
                Point(point.x - offset_x, point.y - offset_y) for point in panel.outline
            ],
            relief_points=[
                Point(point.x - offset_x, point.y - offset_y)
                for point in panel.relief_points
            ],
            stock_index=panel.stock_index,
            stock_origin_x=0.0,
            stock_origin_y=0.0,
        )

    def _write_panel_profiles(
        self, gcode_file, panels: list[Panel], settings: BoxSettings
    ) -> None:
        gcode_file.write(f"(profile cut with {settings.bit_diameter:.3f} mm cutter)\n")
        for panel in panels:
            gcode_file.write(f"({panel.name} panel)\n")
            current_depth = 0.0
            while current_depth > settings.final_cut_depth:
                current_depth = max(
                    current_depth - settings.cut_depth_step, settings.final_cut_depth
                )
                self._write_profile_pass(gcode_file, panel, current_depth, settings)

    def _write_profile_pass(
        self, gcode_file, panel: Panel, depth: float, settings: BoxSettings
    ) -> None:
        original_points = panel.outline
        points = self._offset_closed_outline(panel.outline, settings.bit_diameter * 0.5)
        if len(points) < 2:
            return
        start = points[0]
        gcode_file.write(f"G0 X{start.x:.3f} Y{start.y:.3f}\n")
        gcode_file.write(f"G0 Z{settings.surface_height:.3f}\n")
        gcode_file.write(f"G1 Z{depth:.3f} F{settings.plunge_rate:d}\n")
        gcode_file.write(f"G1 F{settings.feed_rate:d}\n")
        for index, (start, end) in enumerate(zip(points, points[1:])):
            original_start = original_points[index]
            original_end = original_points[index + 1]
            if settings.include_tabs and self._is_bounding_edge(
                panel, original_start, original_end
            ):
                self._write_segment_with_tabs(gcode_file, start, end, depth, settings)
            else:
                gcode_file.write(f"G1 X{end.x:.3f} Y{end.y:.3f}\n")
        gcode_file.write(f"G0 Z{settings.safe_height:.3f}\n")

    def _offset_closed_outline(
        self, points: list[Point], distance: float
    ) -> list[Point]:
        if len(points) < 3 or distance <= 0.0:
            return points
        outline = points[:-1] if points[-1] == points[0] else points
        if len(outline) < 3:
            return points

        signed_area = self._signed_area(outline)
        if abs(signed_area) < 0.001:
            return points

        offset_distance = distance if signed_area > 0.0 else -distance
        offset_points: list[Point] = []
        for index, point in enumerate(outline):
            previous_point = outline[index - 1]
            next_point = outline[(index + 1) % len(outline)]
            previous_line = self._offset_line(previous_point, point, offset_distance)
            next_line = self._offset_line(point, next_point, offset_distance)
            offset_points.append(
                self._line_intersection(previous_line, next_line)
                or self._offset_point(
                    point, previous_point, next_point, offset_distance
                )
            )
        offset_points.append(offset_points[0])
        return offset_points

    def _offset_line(
        self, start: Point, end: Point, distance: float
    ) -> tuple[Point, Point]:
        dx = end.x - start.x
        dy = end.y - start.y
        length = (dx * dx + dy * dy) ** 0.5
        if length <= 0.0001:
            return start, end
        normal_x = dy / length
        normal_y = -dx / length
        return (
            Point(start.x + normal_x * distance, start.y + normal_y * distance),
            Point(end.x + normal_x * distance, end.y + normal_y * distance),
        )

    def _line_intersection(
        self, first: tuple[Point, Point], second: tuple[Point, Point]
    ) -> Point | None:
        first_start, first_end = first
        second_start, second_end = second
        first_dx = first_end.x - first_start.x
        first_dy = first_end.y - first_start.y
        second_dx = second_end.x - second_start.x
        second_dy = second_end.y - second_start.y
        denominator = first_dx * second_dy - first_dy * second_dx
        if abs(denominator) <= 0.0001:
            return None
        offset_x = second_start.x - first_start.x
        offset_y = second_start.y - first_start.y
        distance_on_first = (offset_x * second_dy - offset_y * second_dx) / denominator
        return Point(
            first_start.x + first_dx * distance_on_first,
            first_start.y + first_dy * distance_on_first,
        )

    def _offset_point(
        self, point: Point, previous_point: Point, next_point: Point, distance: float
    ) -> Point:
        previous_dx = point.x - previous_point.x
        previous_dy = point.y - previous_point.y
        next_dx = next_point.x - point.x
        next_dy = next_point.y - point.y
        previous_length = (previous_dx * previous_dx + previous_dy * previous_dy) ** 0.5
        next_length = (next_dx * next_dx + next_dy * next_dy) ** 0.5
        if previous_length <= 0.0001 or next_length <= 0.0001:
            return point
        normal_x = (previous_dy / previous_length) + (next_dy / next_length)
        normal_y = (-previous_dx / previous_length) + (-next_dx / next_length)
        normal_length = (normal_x * normal_x + normal_y * normal_y) ** 0.5
        if normal_length <= 0.0001:
            return point
        return Point(
            point.x + normal_x / normal_length * distance,
            point.y + normal_y / normal_length * distance,
        )

    def _write_segment_with_tabs(
        self, gcode_file, start: Point, end: Point, depth: float, settings: BoxSettings
    ) -> None:
        dx = end.x - start.x
        dy = end.y - start.y
        length = (dx * dx + dy * dy) ** 0.5
        if length < settings.tab_width * 2.0:
            gcode_file.write(f"G1 X{end.x:.3f} Y{end.y:.3f}\n")
            return
        tab_count = self._tab_count_for_segment(length, settings.tab_width)
        ranges = []
        for index in range(tab_count):
            center = length * (index + 1) / (tab_count + 1)
            ranges.append(
                (center - settings.tab_width * 0.5, center + settings.tab_width * 0.5)
            )
        current = 0.0
        for tab_start, tab_end in ranges:
            self._move_along_segment(
                gcode_file, start, dx, dy, length, tab_start, depth
            )
            if depth < -settings.tab_height:
                gcode_file.write(
                    f"G1 Z{-settings.tab_height:.3f} F{settings.plunge_rate:d}\n"
                )
            self._move_along_segment(
                gcode_file,
                start,
                dx,
                dy,
                length,
                tab_end,
                max(depth, -settings.tab_height),
            )
            if depth < -settings.tab_height:
                gcode_file.write(f"G1 Z{depth:.3f} F{settings.plunge_rate:d}\n")
            current = tab_end
        if current < length:
            gcode_file.write(f"G1 X{end.x:.3f} Y{end.y:.3f}\n")

    def _move_along_segment(
        self,
        gcode_file,
        start: Point,
        dx: float,
        dy: float,
        length: float,
        distance: float,
        depth: float,
    ) -> None:
        clamped = max(0.0, min(length, distance))
        ratio = clamped / length
        x_pos = start.x + dx * ratio
        y_pos = start.y + dy * ratio
        gcode_file.write(f"G1 X{x_pos:.3f} Y{y_pos:.3f}\n")

    def _tab_count_for_segment(self, length: float, tab_width: float) -> int:
        if length < tab_width * 4.0:
            return 1
        return 2

    def _is_bounding_edge(self, panel: Panel, start: Point, end: Point) -> bool:
        min_x, max_x, min_y, max_y = panel.bounds
        tolerance = 0.001
        return (
            abs(start.x - end.x) < tolerance
            and (abs(start.x - min_x) < tolerance or abs(start.x - max_x) < tolerance)
        ) or (
            abs(start.y - end.y) < tolerance
            and (abs(start.y - min_y) < tolerance or abs(start.y - max_y) < tolerance)
        )

    def _signed_area(self, outline: list[Point]) -> float:
        area = 0.0
        for start, end in zip(outline, [*outline[1:], outline[0]]):
            area += start.x * end.y - end.x * start.y
        return area * 0.5
